package com.jslx.register.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSchStudentApply<M extends BaseSchStudentApply<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}
	
	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	public M setGrade(java.lang.String grade) {
		set("grade", grade);
		return (M)this;
	}
	
	public java.lang.String getGrade() {
		return getStr("grade");
	}

	public M setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("school_id");
	}

	public M setWishType(java.lang.Boolean wishType) {
		set("wish_type", wishType);
		return (M)this;
	}
	
	public java.lang.Boolean getWishType() {
		return get("wish_type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
