package com.jslx.register.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseSchoolCommunity<M extends BaseBaseSchoolCommunity<M>> extends Model<M> implements IBean {

	public M setSchoolId(java.lang.Integer schoolId) {
		set("school_id", schoolId);
		return (M)this;
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("school_id");
	}

	public M setCommunityId(java.lang.Integer communityId) {
		set("community_id", communityId);
		return (M)this;
	}
	
	public java.lang.Integer getCommunityId() {
		return getInt("community_id");
	}

	public M setSort(java.lang.String sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.String getSort() {
		return getStr("sort");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
