package com.jslx.register.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseSchool<M extends BaseBaseSchool<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setType(java.lang.Boolean type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Boolean getType() {
		return get("type");
	}

	public M setSchoolType(java.lang.Boolean schoolType) {
		set("school_type", schoolType);
		return (M)this;
	}
	
	public java.lang.Boolean getSchoolType() {
		return get("school_type");
	}

	public M setCityId(java.lang.Integer cityId) {
		set("city_id", cityId);
		return (M)this;
	}
	
	public java.lang.Integer getCityId() {
		return getInt("city_id");
	}

	public M setCountyId(java.lang.Integer countyId) {
		set("county_id", countyId);
		return (M)this;
	}
	
	public java.lang.Integer getCountyId() {
		return getInt("county_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
