package com.jslx.register.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseParGuardian<M extends BaseParGuardian<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
		return (M)this;
	}
	
	public java.lang.String getIdcard() {
		return getStr("idcard");
	}

	public M setSex(java.lang.Boolean sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public M setHkbJhrPic(java.lang.String hkbJhrPic) {
		set("hkb_jhr_pic", hkbJhrPic);
		return (M)this;
	}
	
	public java.lang.String getHkbJhrPic() {
		return getStr("hkb_jhr_pic");
	}

	public M setHkbPic(java.lang.String hkbPic) {
		set("hkb_pic", hkbPic);
		return (M)this;
	}
	
	public java.lang.String getHkbPic() {
		return getStr("hkb_pic");
	}

	public M setIdcardPic(java.lang.String idcardPic) {
		set("idcard_pic", idcardPic);
		return (M)this;
	}
	
	public java.lang.String getIdcardPic() {
		return getStr("idcard_pic");
	}

	public M setIdcardPicBack(java.lang.String idcardPicBack) {
		set("idcard_pic_back", idcardPicBack);
		return (M)this;
	}
	
	public java.lang.String getIdcardPicBack() {
		return getStr("idcard_pic_back");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
