package com.jslx.register.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("base_area", "id", BaseArea.class);
		arp.addMapping("base_community", "id", BaseCommunity.class);
		arp.addMapping("base_school", "id", BaseSchool.class);
		// Composite Primary Key order: community_id,school_id
		arp.addMapping("base_school_community", "community_id,school_id", BaseSchoolCommunity.class);
		arp.addMapping("par_guardian", "id", ParGuardian.class);
		arp.addMapping("par_user", "id", ParUser.class);
		arp.addMapping("par_user_address", "id", ParUserAddress.class);
		arp.addMapping("par_user_type", "id", ParUserType.class);
		arp.addMapping("sch_student_apply", "id", SchStudentApply.class);
		arp.addMapping("sys_exception_log", "id", SysExceptionLog.class);
		arp.addMapping("sys_verify_code", "id", SysVerifyCode.class);
	}
}

