package com.jslx.register.model;

import com.jslx.register.model.base.BaseBaseSchool;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseSchool extends BaseBaseSchool<BaseSchool> {
	public static final BaseSchool dao = new BaseSchool().dao();
}
