package com.jslx.register.model;

import com.jslx.register.model.base.BaseBaseCommunity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseCommunity extends BaseBaseCommunity<BaseCommunity> {
	public static final BaseCommunity dao = new BaseCommunity().dao();
}
