package com.jslx.register.model;

import com.jslx.register.model.base.BaseBaseSchoolCommunity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseSchoolCommunity extends BaseBaseSchoolCommunity<BaseSchoolCommunity> {
	public static final BaseSchoolCommunity dao = new BaseSchoolCommunity().dao();
}
