package com.jslx.register.model;

import com.jslx.register.model.base.BaseBaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseArea extends BaseBaseArea<BaseArea> {
	public static final BaseArea dao = new BaseArea().dao();
}
