package com.jslx.register.model;

import com.jslx.register.model.base.BaseParGuardian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParGuardian extends BaseParGuardian<ParGuardian> {
	public static final ParGuardian dao = new ParGuardian().dao();
}
