package com.jslx.register.model;

import com.jslx.register.model.base.BaseParUserType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParUserType extends BaseParUserType<ParUserType> {
	public static final ParUserType dao = new ParUserType().dao();
}
