package com.jslx.register.model;

import com.jslx.register.model.base.BaseParUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParUserAddress extends BaseParUserAddress<ParUserAddress> {
	public static final ParUserAddress dao = new ParUserAddress().dao();
}
