package com.jslx.register.model;

import com.jslx.register.model.base.BaseParUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ParUser extends BaseParUser<ParUser> {
	public static final ParUser dao = new ParUser().dao();
}
