package com.jslx.register.model;

import com.jslx.register.model.base.BaseSchStudentApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SchStudentApply extends BaseSchStudentApply<SchStudentApply> {
	public static final SchStudentApply dao = new SchStudentApply().dao();
}
