package com.jslx.register.model;

import com.jslx.register.model.base.BaseSysExceptionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysExceptionLog extends BaseSysExceptionLog<SysExceptionLog> {
	public static final SysExceptionLog dao = new SysExceptionLog().dao();
}
