package com.jslx.register.model;

import com.jslx.register.model.base.BaseSysVerifyCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysVerifyCode extends BaseSysVerifyCode<SysVerifyCode> {
	public static final SysVerifyCode dao = new SysVerifyCode().dao();
}
